server:
  port: 1223

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    name: sqlite
    url: jdbc:sqlite:./mydatabase.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
